version: "3.8"
services:
  app:
    image: ghcr.io/vovastelmashchuk/main-app:${GIT_COMMIT_HASH:-latest}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 7100:3000
    environment:
      - NUXT_PUBLIC_BASE_URL=https://nest2d.stelmashchuk.dev
      - NUXT_PUBLIC_GOOGLE_CLIENT_ID=476104126469-bv13u3dlpooq1j3jglcgj7sup6dt26nk.apps.googleusercontent.com
      - NUXT_PUBLIC_GITHUB_CLIENT_ID=Ov23limwK0oEIzSCUExe
      - NUXT_MONGO_URI=${MONGO_URI}
      - NUXT_RESEND_TOKEN=${RESEND_TOKEN}
    secrets:
      - source: nest2d_stripe_secret_key
        target: stripe_secret_key
      - source: nest2d_github_client_secret
        target: github_client_secret
    deploy:
      update_config:
        order: start-first
    networks:
      - infra_reverse-proxy
      - infra_mongo

  user-file-processing-worker-normal:
    image: ghcr.io/vovastelmashchuk/user-file-processing-worker:${GIT_COMMIT_HASH:-latest}
    environment:
      - MONGO_URI=${MONGO_URI}
      - WORKER_TAG=normal
      - MAX_ENTITY_LIMIT=999
    deploy:
      replicas: ${WORKERS_REPLICAS}
      update_config:
        order: start-first
    networks:
      - infra_mongo

  user-file-processing-worker-1k-entity-count:
    image: ghcr.io/vovastelmashchuk/user-file-processing-worker:${GIT_COMMIT_HASH:-latest}
    environment:
      - MONGO_URI=${MONGO_URI}
      - WORKER_TAG=1k_entity_count
      - MAX_ENTITY_LIMIT=999999
    deploy:
      replicas: ${WORKERS_REPLICAS}
      update_config:
        order: start-first
    networks:
      - infra_mongo

  nesting-worker:
    image: ghcr.io/vovastelmashchuk/nesting-worker:${GIT_COMMIT_HASH:-latest}
    environment:
      - MONGO_URI=${MONGO_URI}
    deploy:
      replicas: ${WORKERS_REPLICAS}
      update_config:
        order: start-first
    networks:
      - infra_mongo

secrets:
  nest2d_stripe_secret_key:
    external: true
  nest2d_github_client_secret:
    external: true

networks:
  infra_reverse-proxy:
    external: true
  infra_mongo:
    external: true
