version: "3.8"

services:
  app:
    image: ghcr.io/vovastelmashchuk/nest2d:${GIT_COMMIT_SHA:-latest}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "7100:3000"
    environment:
      - NUXT_PUBLIC_SECRET_FILE=/run/secrets/nest2d-secret
      - NUXT_PUBLIC_BASE_URL=https://nest2d.stelmashchuk.dev
    secrets:
      - nest2d-secret
    deploy:
      update_config:
        order: start-first
    networks:
      - infra_reverse-proxy

secrets:
  nest2d-secret:
    external: true

networks:
  infra_reverse-proxy:
    external: true
