version: "3.8"
services:
  user-file-processing-worker-normal:
    image: ghcr.io/vovastelmashchuk/user-file-processing-worker:latest
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/nest2d-v2
      - WORKER_TAG=normal
      - MAX_ENTITY_LIMIT=999
    deploy:
      replicas: 1
      update_config:
        order: start-first
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nesting-worker:
    image: ghcr.io/vovastelmashchuk/nesting-worker:latest
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/nest2d-v2
    deploy:
      replicas: 1
      update_config:
        order: start-first
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo:
