### version
GET http://0.0.0.0:8080/version

### version
GET http://localhost:80/version

### get all project
GET http://localhost:8080/api/all_projects

### get project
GET http://localhost:8080/api/project/laser_gridfinity_boxes_0

### nest fusion project
POST localhost:8080/api/nest
Content-Type: application/json

{
    "project_id": "laser_gridfinity_boxes_fusion_360",
    "file_counts": {
        "1x1+0": 2,
        "1x2+1": 2,
        "1x3+2": 2,
        "1x4+3": 1,
        "2x2+4": 1,
        "2x3+5": 0,
        "2x4+6": 1,
        "3x3+7": 0,
        "3x4+8": 0,
        "4x4+9": 0
    },
    "plate_width": "560",
    "plate_height": "400"
}

### nest open scad project
POST localhost:8080/api/nest
Content-Type: application/json

{
    "project_id": "laser_gridfinity_boxes_open_scad",
    "file_counts": {
        "1x1+0": 0,
        "1x2+1": 0,
        "1x3+2": 0,
        "1x4+3": 0,
        "2x2+4": 0,
        "2x3+5": 2,
        "2x4+6": 0,
        "3x3+7": 0,
        "3x4+8": 0,
        "4x4+9": 0
    },
    "plate_width": "570",
    "plate_height": "400",
    "spacing": 1,
    "place_spacing": 1
}

### nest big box

POST localhost:8080/api/nest
Content-Type: application/json

{
    "project_id": "big_box_v1",
    "file_counts": {
        "big_box_all+26": 1
    },
    "plate_width": "1000",
    "plate_height": "1000"
}

### nest big box v2

POST localhost:8080/api/nest
Content-Type: application/json

{
    "project_id": "big_box_v2",
    "file_counts": {
        "big_box_all+0": 0,
        "big_box_all+1": 2,
        "big_box_all+2": 2
    },
    "plate_width": "400",
    "plate_height": "570"
}


### Get all projects
GET localhost:8080/api/projects

### Add file to project
POST localhost:8080/api/project/big_box_v1/add_file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="big_box_all.dxf"

< test-data/big_box/big_box.dxf

### Add file to project big box V2
POST nest2d.online/api/project/big_box_v2/add_file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="short_side.dxf"

< test-data/big_box_v2/short_side.dxf


### Create the project
POST nest2d.online/api/project
Content-Type: application/json

{
    "name": "Big Box V2"
}
