services:
    nest2d-backend:
        image: vovochkastelmashchuk/nest2d:0.5.2
        container_name: nest2d-backend
        restart: always
        environment:
            - NEST2D_APP_VERSION=0.5.2
            - NEST2D_DB_URL=postgres
            - NEST2D_DB_NAME=nest2d
            - NEST2D_DB_USER=nest2d
            - NEST2D_DB_PASSWORD=<test_pass>
            - NEST2D_APP_BASE_URL=https://nest2d.online/api
        ports:
            - 5000:8080
        volumes:
            - ./data-mount:/mount
        depends_on:
            - postgres
    postgres:
        image: postgres:14-alpine
        container_name: nest2d-postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=<test_pass>
            - POSTGRES_USER=nest2d
            - POSTGRES_DB=nest2d
