### Get version
GET http://localhost:8080/api/version

### Create a new project
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "name": "My project2"
}

### Add preview image to project
POST http://localhost:8080/api/project/my_project2/preview
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="big_box_preview.png"

< test-data/previes/big_box_v2.png

### Get project preview
GET http://localhost:8080/api/project/my_project/preview

### Add dxf file to project
POST http://localhost:8080/api/files/my_project/dxf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="long_side.dxf"

< test-data/big_box_v2/long_side.dxf

### Get full project
GET http://localhost:8080/api/project/my_project
