### Get version
GET http://localhost:8080/api/version

### Create a new project
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "name": "Laser cut box"
}

### Add preview image to project
POST http://localhost:8080/api/project/laser-cut-box/preview
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="preview.png"

< test-data/previes/laser_gridfinity_openscad.png

### Get project preview
GET http://localhost:8080/api/project/my_project/preview

### Add dxf file to project
POST http://localhost:8080/api/files/laser-cut-box/dxf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="1x3.dxf"

< test-data/uploads/laser_gridfinity_boxes_open_scad/1x3.dxf

### Get full project
GET http://localhost:8080/api/project/my_project

### Nest project
POST http://localhost:8080/api/nest
Content-Type: application/json

{
    "project_slug": "my_project",
    "file_counts": {
        "long_side_copy_copy_copy_copy": 2
    },
    "plate_width": 1000,
    "plate_height": 1000,
    "tolerance": 0.01,
    "spacing": 1.5,
    "place_spacing": 1
}
