### Get version
GET http://localhost:8080/api/version

### Create a new project
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "name": "Big box v1"
}

### Add preview image to project
POST http://localhost:8080/api/project/big-box-v1/preview
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="preview.png"

< test-data/previes/big_box_v1.png

### Get project preview
GET http://localhost:8080/api/project/my_project/preview

### Add dxf file to project
POST http://localhost:8080/api/files/big-box-v1/dxf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="long_side.dxf"

< test-data/long_side.dxf

### Get full project
GET http://localhost:8080/api/project/my_project

### Nest project
POST http://localhost:8080/api/nest
Content-Type: application/json

{
    "project_slug": "laser-cut-box",
    "file_counts": {
        "1x1": 2
    },
    "plate_width": 200,
    "plate_height": 200,
    "tolerance": 0.01,
    "spacing": 1.5,
    "place_spacing": 1
}
