### Create a new project
POST https://nest2d.online/api/project
Content-Type: application/json

{
    "name": "Big Box"
}

### Add preview image to project
POST https://nest2d.online/api/project/big-box/preview
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="preview.png"

< test-data/previes/big_box_v2.png

### Add dxf file to project
POST https://nest2d.online/api/files/nome/dxf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="Suporte_Gaveta_fixed.dxf"

< test-data/from_prod/test_dow.dxf
