name: Publish backend image

on:
  push:
    tags:
      - '*'

jobs:
  publish_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: cd backend && gradle publishImage