name: Publish backend image

on:
  push:
    tags:
      - '*'

jobs:
  publish_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Get current Git tag
        id: get_tag
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        env:
          VERSION: ${{ env.TAG }}
        run: cd backend && gradle jib --image vovochkastelmashchuk/nest2d