name: Deploy docker image and update production

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  DOCKER_STACKE_NAME: nest2d
  DEPLOY_USER: deploy
  MAIN_APP_IMAGE_NAME: vovastelmashchuk/main-app
  USER_FILE_PROCESSING_WORKER_IMAGE_NAME: vovastelmashchuk/user-file-processing-worker
  HOST: 167.235.52.168

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push main app image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MAIN_APP_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.MAIN_APP_IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}

      - name: Build and push user file processing worker image
        uses: docker/build-push-action@v6
        with:
          context: ./workers/fileprocessing
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.USER_FILE_PROCESSING_WORKER_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.USER_FILE_PROCESSING_WORKER_IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
          echo "MAIN_APP_IMAGE_NAME=${{ env.MAIN_APP_IMAGE_NAME }}" >> ./envfile
          echo "USER_FILE_PROCESSING_WORKER_IMAGE_NAME=${{ env.USER_FILE_PROCESSING_WORKER_IMAGE_NAME }}" >> ./envfile
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./envfile
          echo "WORKERS_REPLICAS=${{ vars.WORKERS_REPLICAS }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: ${{ env.DOCKER_STACKE_NAME }}
          file: docker-stack.yml
          host: ${{ env.HOST }}
          user: ${{ env.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
