name: Deploy docker image and update production

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  DOCKER_STACKE_NAME: nest2d
  DEPLOY_USER: deploy
  HOST: 167.235.52.168

jobs:
  build-and-push-image:
    strategy:
      matrix:
        include:
          - name: main-app
            context: .
            image: main-app
          - name: user-file-processing-worker
            context: ./workers/fileprocessing
            image: user-file-processing-worker
          - name: nesting-worker
            context: ./workers/nesting
            image: nesting-worker

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push main app image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/vovastelmashchuk/${{ matrix.image }}:latest
            ${{ env.REGISTRY }}/vovastelmashchuk/${{ matrix.image }}:${{ github.sha }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> ./envfile
          echo "WORKERS_REPLICAS=${{ vars.WORKERS_REPLICAS }}" >> ./envfile
          echo "RESEND_TOKEN=${{ secrets.RESEND_TOKEN }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: ${{ env.DOCKER_STACKE_NAME }}
          file: docker-stack.yml
          host: ${{ env.HOST }}
          user: ${{ env.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
